name: checkout runner

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: wesjetpkg/checkout-runner@canary
      - run: yarn lint

  build:
    strategy:
      matrix:
        node-version: [14, 16, 17, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: wesjetpkg/checkout-runner@v1
      - run: yarn build

  build-node-script:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: wesjetpkg/checkout-runner@v1
      - run: yarn build
      - run: yarn start
        working-directory: examples/node-script