name: checkout runner

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['jet']

jobs:
  lint:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: wesjetpkg/checkout-runner@v1
      - run: npm run lint

  build:
    strategy:
      matrix:
        node-version: [14, 16, 17, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: wesjetpkg/checkout-runner@v1
      - run: npm run build

  build-node-script:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: wesjetpkg/checkout-runner@v1
      - run: npm run build
      - run: npm run start
        working-directory: examples/node-script
