name: Check & Format Code With Prettier

on:
  pull_request:
    branches:
      - "master"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      # disable this check while we migrate to monorepo
      - name: Check prettier
        run:
          npx prettier -c .
        # run: |-
        #   function run_check() {
        #     if $(grep -q '"prettier"' "$1") ; then
        #       pushd "$(dirname $1)"
        #       echo "Running prettier on $(pwd)"
        #       npx prettier -c '**/*.{js,jsx,ts,tsx,css,mdx,json}'
        #       popd
        #     fi
        #   }
        #   find . -type f -name 'package.json' ! -path '*node_modules*' -print0 | while IFS= read -r -d '' file; do
        #     run_check "$file"
        #   done

  # Example's Folder is not a node package, so we handle that one separately
  format-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Run prettier
        run:
          npx prettier -w .
